name: deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - shell: bash
        run: |
          aws cloudformation deploy \
            --stack-name ${{ vars.STACK_NAME }} \
            --template-file cloudformation.yml \
            --role-arn ${{ vars.CLOUDFORMATION_ROLE_ARN }}
